site_name: PyTabular
site_url: https://curts0.github.io/PyTabular/
nav:
    - Home: index.md
    - Tabular: Tabular.md
    - Table: Table.md
    - Partition: Partition.md
    - Column: Column.md
    - Measure: Measure.md
    - Trace: Traces.md
    - Queries: Queries.md
    - Best Practice Analyzer: Best Practice Analyzer.md
    - Tabular Editor: Tabular Editor 2.md
    - PBI Helper: PBI Helper.md
    - Logic Utils: Logic Utils.md
theme: readthedocs
